# This is to test new workflow

name: Run test with multiple MATLAB releases using matrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - 'code/*.m'
    paths-ignore:
      - '.github/workflows/**'
