# This workflow helps in testing MATLAB toolbox for multiple releases using smoke test tool

name: Use smoke test tool to test toolbox against different MATLAB release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "developmentn" branch
  push:
    branches:
      - development      
      
jobs:
  # This workflow contains:
  # 1. a matrixed test job run across a bunch of releases of MATLAB
  # 2. a reporting script which generates diff reports to show failed test comparison and individual diff reports
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        MATLABVersion: [R2021a, R2021b, R2022a, R2022b, R2023a]
        include:
          - MATLABVersion: R2023a
            reportGenerate: 1

    steps:
      - name: Checkout CDT branch
        uses: actions/checkout@v3
        with:
          repository: Mikhil11/TestCDT

      - name: Checkout smoke testing repo
        run: |
          git clone https://github.com/Mikhil11/smokeTesting.git
      
      - name: Set up new MATLAB release
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.MATLABVersion }}

      # This mat file contains Failed test results object for different MATLAB release   
      - name: Download MAT file
        # Nothing to download for the first case
        if: ${{ matrix.MATLABVersion != 'R2021a' }}
        uses: actions/download-artifact@v3
        with:
          name: save-mat-file
       
      # Individual test reports for a given MATLAB release is stored in testresults folder
      - name: Download testresults directory
        # Nothing to download for the first case
        if: ${{ matrix.MATLABVersion != 'R2021a' }}
        uses: actions/download-artifact@v3
        with:
          name: save-test-results
          path: testresults

      # Runs all the doc scripts in cdt/doc folder.  The test results are added to 'testresults' folder
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('smokeTesting'),addpath(genpath('cdt')),runRapidTester("${{ matrix.MATLABVersion }}");
          
      # The uploaded mat file contains Failed test results object for different MATLAB release. The details are in runRapidTester.m file     
      - name: Upload MAT file
        uses: actions/upload-artifact@v3
        with:
          name: save-mat-file
          path: mystructfilenew.mat
      
      # Test results for each MATLAB version is uploaded
      - name: Upload test folder
        uses: actions/upload-artifact@v3
        with:
          name: save-test-results
          path: testresults/
       
      # All failed results are stored in the MAT file which is loaded here and comparison html report is generated using generateHtmlTestreport.m function
      - name: Create HTML report
        if: ${{ matrix.reportGenerate }}
        uses: matlab-actions/run-command@v1
        with:
          command: load('mystructfilenew.mat'),addpath('smokeTesting'),generateHtmlTestReport('mystructfilenew.mat');
          
      # Commit all testresults and diff html report into the repository
      - name: Commit test report
        if: ${{ matrix.reportGenerate }}
        continue-on-error: true
        run: |
          git config --global user.email "mikhils@mathworks.com" && git config --global user.name "Mikhil11"
          git remote add development https://github.com/Mikhil11/TestCDT.git
          git remote -v
          git add testresults/.
          git commit -m "new testing commit"
          git push -u origin development
